### PR TITLE
Add communication media

### PR DESCRIPTION
**Pull request by romain-michalec**
Images for communication purposes (*Inside Strathclyde* newsletter), made from free-to-use resources:

* [Computer code blending in a picture of a radio telescope](https://raw.githubusercontent.com/strathclyde-rse/strathy_software_survey_analysis_2020/communication-media/pictures/radio-astronomy.jpg)
* [Computer code blending in a picture of an orbital launch vehicle taking off](https://raw.githubusercontent.com/strathclyde-rse/strathy_software_survey_analysis_2020/communication-media/pictures/orbital-launch-vehicle.jpg)
* [Subject icons for each faculty on a picture of a printed circuit board (faculty colors)](https://raw.githubusercontent.com/strathclyde-rse/strathy_software_survey_analysis_2020/communication-media/pictures/subject-symbols-lineal.png)
* [Subject icons for each faculty on a picture of a printed circuit board (color icons)](https://raw.githubusercontent.com/strathclyde-rse/strathy_software_survey_analysis_2020/communication-media/pictures/subject-symbols-lineal-color.png)

See [credits.md](https://github.com/strathclyde-rse/strathy_software_survey_analysis_2020/blob/communication-media/pictures/credits.md) as the subject icons require attribution.

### CODE REVIEW

**Comment by widdowquinn** [comment]
I like the subject icons best, with a slight preference for faculty colours.

**Comment by romain-michalec** [comment]
I hope that the faculty colors will be eye-catching and immediately relatable for everyone.

I'm concerned that the image will look a lot less crisp once scaled down for inclusion in the newsletter (see below at 250 px wide). Should I try and make the circles/icons larger? Or perhaps one unique larger circle, split in four colored quarters, so that the icons can be larger too?

Also, if anyone's got their own electronics/computer-related background they'd like to showcase, feel free to let us know!

subject-symbols-lineal-250px

**Comment by drt24** [comment]
No I think that is fine. As long as they get sized from the SVG there shouldn't be a problem.

**Comment by romain-michalec** [comment]
> As long as they get sized from the SVG there shouldn't be a problem.

I thought so too but the image in my previous comment was sized from the SVG and it shows this noticeable blurriness. Perhaps I'm doing something wrong.

I've tried scaling down a large raster image exported from the SVG, instead of directly exporting a small raster image, but this predictably only yields worse or similar results. I've tried it different ways too, such as scaling down without pixel averaging (nearest neighbor method), scaling down by an integer factor (subsampling), or the recommended method of applying a Gaussian blur of as many pixels as the resizing factor (anti-aliasing).

What apparently gives the least worst result is to compensate the blur by applying a sharpening filter (e.g. _GIMP > Filters > Enhance > Sharpen_) to the image sized from the SVG.

And it's probably not so important anyway because the final image will be resized/anti-aliased again according to window size when displayed on the reader's screen.

**Pull request merged**
